version: "3"
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:$KIBANA_VERSION
    container_name: kibana01-labs
    environment:
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=$ELASTIC_PASSWORD
    networks:
      - efk-network
    ports:
      - "5601:5601"
networks:
  efk-network:
    external: true
    name: efk-network
